// Generated by scripts/build-address-pool.js. Do not edit by hand.
// Source: data/address-pool/*.json
// Generated at: 2026-05-10T14:13:10.154Z
const LOCAL_VERIFIED_ADDRESS_POOL_DATA = {
  "Australia": [
    {
      "address": "1 Macquarie St",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "200 George St",
      "city": "Sydney",
      "state": "New South Wales",
      "zipCode": "2000"
    },
    {
      "address": "101 Collins St",
      "city": "Melbourne",
      "state": "Victoria",
      "zipCode": "3000"
    },
    {
      "address": "480 Queen St",
      "city": "Brisbane",
      "state": "Queensland",
      "zipCode": "4000"
    },
    {
      "address": "240 St Georges Terrace",
      "city": "Perth",
      "state": "Western Australia",
      "zipCode": "6000"
    },
    {
      "address": "1 King William St",
      "city": "Adelaide",
      "state": "South Australia",
      "zipCode": "5000"
    },
    {
      "address": "15 London Cct",
      "city": "Canberra",
      "state": "Australian Capital Territory",
      "zipCode": "2601"
    },
    {
      "address": "89 Macquarie St",
      "city": "Hobart",
      "state": "Tasmania",
      "zipCode": "7000"
    },
    {
      "address": "12 Smith St",
      "city": "Darwin",
      "state": "Northern Territory",
      "zipCode": "0800"
    },
    {
      "address": "50 Cavill Ave",
      "city": "Gold Coast",
      "state": "Queensland",
      "zipCode": "4217"
    }
  ],
  "Brazil": [
    {
      "address": "Avenida Paulista 1578",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01310-200"
    },
    {
      "address": "Rua Augusta 1200",
      "city": "Sao Paulo",
      "state": "Sao Paulo",
      "zipCode": "01304-001"
    },
    {
      "address": "Avenida Atlantica 1702",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22021-001"
    },
    {
      "address": "Rua do Catete 120",
      "city": "Rio de Janeiro",
      "state": "Rio de Janeiro",
      "zipCode": "22220-000"
    },
    {
      "address": "SCS Quadra 2 Bloco C",
      "city": "Brasilia",
      "state": "Federal District",
      "zipCode": "70300-902"
    },
    {
      "address": "Avenida Sete de Setembro 2500",
      "city": "Salvador",
      "state": "Bahia",
      "zipCode": "40080-001"
    },
    {
      "address": "Avenida Beira Mar 2200",
      "city": "Fortaleza",
      "state": "Ceara",
      "zipCode": "60165-121"
    },
    {
      "address": "Avenida Afonso Pena 3000",
      "city": "Belo Horizonte",
      "state": "Minas Gerais",
      "zipCode": "30130-009"
    },
    {
      "address": "Rua XV de Novembro 450",
      "city": "Curitiba",
      "state": "Parana",
      "zipCode": "80020-310"
    },
    {
      "address": "Avenida Boa Viagem 800",
      "city": "Recife",
      "state": "Pernambuco",
      "zipCode": "51011-000"
    }
  ],
  "Canada": [
    {
      "address": "111 Wellington St",
      "city": "Ottawa",
      "state": "Ontario",
      "zipCode": "K1A 0A9"
    },
    {
      "address": "250 Yonge St",
      "city": "Toronto",
      "state": "Ontario",
      "zipCode": "M5B 2L7"
    },
    {
      "address": "100 Queen St W",
      "city": "Toronto",
      "state": "Ontario",
      "zipCode": "M5H 2N2"
    },
    {
      "address": "845 Hornby St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V6Z 1V1"
    },
    {
      "address": "655 Burrard St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V6C 2R7"
    },
    {
      "address": "1380 Sherbrooke St W",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H3G 1J5"
    },
    {
      "address": "10 Rue Sainte-Catherine O",
      "city": "Montreal",
      "state": "Quebec",
      "zipCode": "H2X 1Z6"
    },
    {
      "address": "9700 Jasper Ave",
      "city": "Edmonton",
      "state": "Alberta",
      "zipCode": "T5J 4C3"
    },
    {
      "address": "200 Portage Ave",
      "city": "Winnipeg",
      "state": "Manitoba",
      "zipCode": "R3C 4X2"
    },
    {
      "address": "700 W Georgia St",
      "city": "Vancouver",
      "state": "British Columbia",
      "zipCode": "V7Y 1K8"
    }
  ],
  "China": [
    {
      "address": "1 Chang an Avenue",
      "city": "Beijing",
      "state": "Beijing",
      "zipCode": "100006"
    },
    {
      "address": "99 Wangfujing Street",
      "city": "Beijing",
      "state": "Beijing",
      "zipCode": "100005"
    },
    {
      "address": "100 Nanjing Road East",
      "city": "Shanghai",
      "state": "Shanghai",
      "zipCode": "200001"
    },
    {
      "address": "88 Huaihai Road",
      "city": "Shanghai",
      "state": "Shanghai",
      "zipCode": "200020"
    },
    {
      "address": "200 Tianhe Road",
      "city": "Guangzhou",
      "state": "Guangdong",
      "zipCode": "510620"
    },
    {
      "address": "1 Shennan Avenue",
      "city": "Shenzhen",
      "state": "Guangdong",
      "zipCode": "518000"
    },
    {
      "address": "168 West Lake Avenue",
      "city": "Hangzhou",
      "state": "Zhejiang",
      "zipCode": "310007"
    },
    {
      "address": "300 Jiefang Road",
      "city": "Chengdu",
      "state": "Sichuan",
      "zipCode": "610015"
    },
    {
      "address": "66 Zhongshan Road",
      "city": "Nanjing",
      "state": "Jiangsu",
      "zipCode": "210005"
    },
    {
      "address": "88 Renmin Road",
      "city": "Wuhan",
      "state": "Hubei",
      "zipCode": "430014"
    }
  ],
  "France": [
    {
      "address": "10 Avenue des Champs-Elysees",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75008"
    },
    {
      "address": "16 Boulevard Haussmann",
      "city": "Paris",
      "state": "Ile-de-France",
      "zipCode": "75009"
    },
    {
      "address": "20 Rue de la Republique",
      "city": "Lyon",
      "state": "Auvergne-Rhone-Alpes",
      "zipCode": "69002"
    },
    {
      "address": "1 Quai du Port",
      "city": "Marseille",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "13002"
    },
    {
      "address": "12 Place de la Comedie",
      "city": "Montpellier",
      "state": "Occitanie",
      "zipCode": "34000"
    },
    {
      "address": "8 Rue Sainte-Catherine",
      "city": "Bordeaux",
      "state": "Nouvelle-Aquitaine",
      "zipCode": "33000"
    },
    {
      "address": "2 Place du Capitole",
      "city": "Toulouse",
      "state": "Occitanie",
      "zipCode": "31000"
    },
    {
      "address": "5 Rue Faidherbe",
      "city": "Lille",
      "state": "Hauts-de-France",
      "zipCode": "59000"
    },
    {
      "address": "3 Rue du Dome",
      "city": "Strasbourg",
      "state": "Grand Est",
      "zipCode": "67000"
    },
    {
      "address": "7 Avenue Jean Medecin",
      "city": "Nice",
      "state": "Provence-Alpes-Cote d Azur",
      "zipCode": "06000"
    }
  ],
  "Germany": [
    {
      "address": "Unter den Linden 10",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Friedrichstrasse 100",
      "city": "Berlin",
      "state": "Berlin",
      "zipCode": "10117"
    },
    {
      "address": "Mönckebergstrasse 7",
      "city": "Hamburg",
      "state": "Hamburg",
      "zipCode": "20095"
    },
    {
      "address": "Kaufingerstrasse 15",
      "city": "Munich",
      "state": "Bavaria",
      "zipCode": "80331"
    },
    {
      "address": "Schildergasse 45",
      "city": "Cologne",
      "state": "North Rhine-Westphalia",
      "zipCode": "50667"
    },
    {
      "address": "Zeil 60",
      "city": "Frankfurt",
      "state": "Hesse",
      "zipCode": "60313"
    },
    {
      "address": "Königstrasse 28",
      "city": "Stuttgart",
      "state": "Baden-Württemberg",
      "zipCode": "70173"
    },
    {
      "address": "Königsallee 30",
      "city": "Düsseldorf",
      "state": "North Rhine-Westphalia",
      "zipCode": "40212"
    },
    {
      "address": "Prager Strasse 12",
      "city": "Dresden",
      "state": "Saxony",
      "zipCode": "01069"
    },
    {
      "address": "Petersstrasse 20",
      "city": "Leipzig",
      "state": "Saxony",
      "zipCode": "04109"
    }
  ],
  "Hong Kong": [
    {
      "address": "1 Connaught Place",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "10 Des Voeux Road Central",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "18 Salisbury Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "8 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "555 Hennessy Road",
      "city": "Causeway Bay",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "388 Prince Edward Road",
      "city": "Kowloon",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "99 Queen's Road East",
      "city": "Central",
      "state": "Hong Kong Island",
      "zipCode": ""
    },
    {
      "address": "1 Austin Road West",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    },
    {
      "address": "12 Sha Tin Centre Street",
      "city": "Sha Tin",
      "state": "New Territories",
      "zipCode": ""
    },
    {
      "address": "33 Canton Road",
      "city": "Tsim Sha Tsui",
      "state": "Kowloon",
      "zipCode": ""
    }
  ],
  "India": [
    {
      "address": "12 MG Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400001"
    },
    {
      "address": "45 Linking Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "zipCode": "400050"
    },
    {
      "address": "8 Connaught Place",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110001"
    },
    {
      "address": "120 Janpath",
      "city": "Delhi",
      "state": "Delhi",
      "zipCode": "110011"
    },
    {
      "address": "50 Brigade Road",
      "city": "Bangalore",
      "state": "Karnataka",
      "zipCode": "560001"
    },
    {
      "address": "18 Park Street",
      "city": "Kolkata",
      "state": "West Bengal",
      "zipCode": "700016"
    },
    {
      "address": "32 Anna Salai",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "zipCode": "600002"
    },
    {
      "address": "5 Residency Road",
      "city": "Hyderabad",
      "state": "Telangana",
      "zipCode": "500001"
    },
    {
      "address": "66 Ashram Road",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "zipCode": "380009"
    },
    {
      "address": "14 FC Road",
      "city": "Pune",
      "state": "Maharashtra",
      "zipCode": "411004"
    }
  ],
  "Italy": [
    {
      "address": "Via del Corso 120",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00186"
    },
    {
      "address": "Via Nazionale 45",
      "city": "Rome",
      "state": "Lazio",
      "zipCode": "00184"
    },
    {
      "address": "Via Torino 61",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20123"
    },
    {
      "address": "Corso Buenos Aires 15",
      "city": "Milan",
      "state": "Lombardy",
      "zipCode": "20124"
    },
    {
      "address": "Via Toledo 220",
      "city": "Naples",
      "state": "Campania",
      "zipCode": "80134"
    },
    {
      "address": "Via Roma 90",
      "city": "Turin",
      "state": "Piedmont",
      "zipCode": "10121"
    },
    {
      "address": "Via Maqueda 75",
      "city": "Palermo",
      "state": "Sicily",
      "zipCode": "90133"
    },
    {
      "address": "Via XX Settembre 40",
      "city": "Genoa",
      "state": "Liguria",
      "zipCode": "16121"
    },
    {
      "address": "Via Rizzoli 12",
      "city": "Bologna",
      "state": "Emilia-Romagna",
      "zipCode": "40125"
    },
    {
      "address": "Via de Tornabuoni 18",
      "city": "Florence",
      "state": "Tuscany",
      "zipCode": "50123"
    }
  ],
  "Japan": [
    {
      "address": "1-1 Chiyoda",
      "city": "Tokyo",
      "state": "Tokyo",
      "zipCode": "100-8111"
    },
    {
      "address": "2-8-1 Nishi-Shinjuku",
      "city": "Tokyo",
      "state": "Tokyo",
      "zipCode": "163-8001"
    },
    {
      "address": "3-1-1 Umeda",
      "city": "Osaka",
      "state": "Osaka",
      "zipCode": "530-0001"
    },
    {
      "address": "1-2-3 Minato Mirai",
      "city": "Yokohama",
      "state": "Kanagawa",
      "zipCode": "220-0012"
    },
    {
      "address": "1-1 Sakae",
      "city": "Nagoya",
      "state": "Aichi",
      "zipCode": "460-0008"
    },
    {
      "address": "2-5 Kita 5 Jo Nishi",
      "city": "Sapporo",
      "state": "Hokkaido",
      "zipCode": "060-0005"
    },
    {
      "address": "1-1 Tenjin",
      "city": "Fukuoka",
      "state": "Fukuoka",
      "zipCode": "810-0001"
    },
    {
      "address": "2-2-1 Sannomiya",
      "city": "Kobe",
      "state": "Hyogo",
      "zipCode": "650-0021"
    },
    {
      "address": "1-1 Shijo-dori",
      "city": "Kyoto",
      "state": "Kyoto",
      "zipCode": "600-8001"
    },
    {
      "address": "1-3-1 Sendai Aoba",
      "city": "Sendai",
      "state": "Miyagi",
      "zipCode": "980-0811"
    }
  ],
  "Mexico": [
    {
      "address": "Avenida Paseo de la Reforma 222",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06600"
    },
    {
      "address": "Calle Madero 10",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "06000"
    },
    {
      "address": "Avenida Juarez 99",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44100"
    },
    {
      "address": "Calle Morelos 120",
      "city": "Guadalajara",
      "state": "Jalisco",
      "zipCode": "44160"
    },
    {
      "address": "Avenida Constitucion 400",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64000"
    },
    {
      "address": "Calle 5 de Mayo 88",
      "city": "Puebla",
      "state": "Puebla",
      "zipCode": "72000"
    },
    {
      "address": "Avenida Revolucion 1550",
      "city": "Tijuana",
      "state": "Baja California",
      "zipCode": "22000"
    },
    {
      "address": "Boulevard Kukulkan 31",
      "city": "Cancun",
      "state": "Quintana Roo",
      "zipCode": "77500"
    },
    {
      "address": "Avenida Universidad 300",
      "city": "Mexico City",
      "state": "Mexico City",
      "zipCode": "04360"
    },
    {
      "address": "Avenida Hidalgo 55",
      "city": "Monterrey",
      "state": "Nuevo Leon",
      "zipCode": "64010"
    }
  ],
  "Netherlands": [
    {
      "address": "Damrak 1",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012LG"
    },
    {
      "address": "Kalverstraat 25",
      "city": "Amsterdam",
      "state": "North Holland",
      "zipCode": "1012NX"
    },
    {
      "address": "Coolsingel 100",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012AG"
    },
    {
      "address": "Lijnbaan 1",
      "city": "Rotterdam",
      "state": "South Holland",
      "zipCode": "3012EK"
    },
    {
      "address": "Vredenburg 40",
      "city": "Utrecht",
      "state": "Utrecht",
      "zipCode": "3511BD"
    },
    {
      "address": "Grote Markt 1",
      "city": "Groningen",
      "state": "Groningen",
      "zipCode": "9712HN"
    },
    {
      "address": "Markt 10",
      "city": "Eindhoven",
      "state": "North Brabant",
      "zipCode": "5611EC"
    },
    {
      "address": "Spuistraat 200",
      "city": "The Hague",
      "state": "South Holland",
      "zipCode": "2511BW"
    },
    {
      "address": "Stationsplein 45",
      "city": "Arnhem",
      "state": "Gelderland",
      "zipCode": "6811KG"
    },
    {
      "address": "Mariastraat 11",
      "city": "Haarlem",
      "state": "North Holland",
      "zipCode": "2011LP"
    }
  ],
  "Russia": [
    {
      "address": "1 Tverskaya Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "125009"
    },
    {
      "address": "15 Arbat Street",
      "city": "Moscow",
      "state": "Moscow",
      "zipCode": "119019"
    },
    {
      "address": "100 Nevsky Prospect",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191025"
    },
    {
      "address": "20 Liteyny Avenue",
      "city": "Saint Petersburg",
      "state": "Saint Petersburg",
      "zipCode": "191014"
    },
    {
      "address": "8 Krasny Prospekt",
      "city": "Novosibirsk",
      "state": "Novosibirsk Oblast",
      "zipCode": "630099"
    },
    {
      "address": "35 Lenina Avenue",
      "city": "Yekaterinburg",
      "state": "Sverdlovsk Oblast",
      "zipCode": "620014"
    },
    {
      "address": "12 Bauman Street",
      "city": "Kazan",
      "state": "Tatarstan",
      "zipCode": "420111"
    },
    {
      "address": "60 Bolshaya Pokrovskaya",
      "city": "Nizhny Novgorod",
      "state": "Nizhny Novgorod Oblast",
      "zipCode": "603005"
    },
    {
      "address": "22 Kirovka Street",
      "city": "Chelyabinsk",
      "state": "Chelyabinsk Oblast",
      "zipCode": "454091"
    },
    {
      "address": "44 Leningradskaya Street",
      "city": "Samara",
      "state": "Samara Oblast",
      "zipCode": "443099"
    }
  ],
  "Singapore": [
    {
      "address": "1 Raffles Place",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "048616"
    },
    {
      "address": "2 Orchard Turn",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "238801"
    },
    {
      "address": "10 Bayfront Avenue",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "018956"
    },
    {
      "address": "50 Jurong Gateway Road",
      "city": "Jurong East",
      "state": "West Region",
      "zipCode": "608549"
    },
    {
      "address": "21 Tampines Avenue 1",
      "city": "Tampines",
      "state": "East Region",
      "zipCode": "529757"
    },
    {
      "address": "1 Woodlands Square",
      "city": "Woodlands",
      "state": "North Region",
      "zipCode": "738099"
    },
    {
      "address": "311 New Upper Changi Road",
      "city": "Bedok",
      "state": "East Region",
      "zipCode": "467360"
    },
    {
      "address": "53 Ang Mo Kio Avenue 3",
      "city": "Ang Mo Kio",
      "state": "North-East Region",
      "zipCode": "569933"
    },
    {
      "address": "200 Victoria Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "188021"
    },
    {
      "address": "30 Bencoolen Street",
      "city": "Singapore",
      "state": "Central Region",
      "zipCode": "189621"
    }
  ],
  "South Korea": [
    {
      "address": "110 Sejong-daero",
      "city": "Seoul",
      "state": "Seoul",
      "zipCode": "04524"
    },
    {
      "address": "231 Teheran-ro",
      "city": "Seoul",
      "state": "Seoul",
      "zipCode": "06142"
    },
    {
      "address": "1 Jungang-daero",
      "city": "Busan",
      "state": "Busan",
      "zipCode": "48939"
    },
    {
      "address": "160 Incheon-daero",
      "city": "Incheon",
      "state": "Incheon",
      "zipCode": "22382"
    },
    {
      "address": "100 Dalseong-ro",
      "city": "Daegu",
      "state": "Daegu",
      "zipCode": "41911"
    },
    {
      "address": "101 Dunsan-ro",
      "city": "Daejeon",
      "state": "Daejeon",
      "zipCode": "35242"
    },
    {
      "address": "50 Geumnam-ro",
      "city": "Gwangju",
      "state": "Gwangju",
      "zipCode": "61482"
    },
    {
      "address": "85 Gwonseon-ro",
      "city": "Suwon",
      "state": "Gyeonggi",
      "zipCode": "16488"
    },
    {
      "address": "22 Namgu-ro",
      "city": "Ulsan",
      "state": "Ulsan",
      "zipCode": "44675"
    },
    {
      "address": "12 Changwon-daero",
      "city": "Changwon",
      "state": "South Gyeongsang",
      "zipCode": "51435"
    }
  ],
  "Spain": [
    {
      "address": "Gran Via 1",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28013"
    },
    {
      "address": "Calle de Alcala 45",
      "city": "Madrid",
      "state": "Madrid",
      "zipCode": "28014"
    },
    {
      "address": "La Rambla 91",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08002"
    },
    {
      "address": "Passeig de Gracia 60",
      "city": "Barcelona",
      "state": "Catalonia",
      "zipCode": "08007"
    },
    {
      "address": "Calle Colon 12",
      "city": "Valencia",
      "state": "Valencia",
      "zipCode": "46004"
    },
    {
      "address": "Calle Sierpes 5",
      "city": "Seville",
      "state": "Andalusia",
      "zipCode": "41004"
    },
    {
      "address": "Calle Larios 8",
      "city": "Malaga",
      "state": "Andalusia",
      "zipCode": "29005"
    },
    {
      "address": "Calle Mayor 20",
      "city": "Zaragoza",
      "state": "Aragon",
      "zipCode": "50001"
    },
    {
      "address": "Gran Via Don Diego Lopez de Haro 12",
      "city": "Bilbao",
      "state": "Basque Country",
      "zipCode": "48001"
    },
    {
      "address": "Calle Traperia 3",
      "city": "Murcia",
      "state": "Murcia",
      "zipCode": "30001"
    }
  ],
  "Taiwan": [
    {
      "address": "No. 1, Zhongxiao W Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "100"
    },
    {
      "address": "No. 45, Xinyi Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "110"
    },
    {
      "address": "No. 12, Sanduo 4th Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "802"
    },
    {
      "address": "No. 88, Taiwan Blvd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "400"
    },
    {
      "address": "No. 20, Minsheng Rd",
      "city": "Tainan",
      "state": "Tainan City",
      "zipCode": "700"
    },
    {
      "address": "No. 10, Fuxing Rd",
      "city": "Hsinchu",
      "state": "Hsinchu City",
      "zipCode": "300"
    },
    {
      "address": "No. 66, Zhongshan Rd",
      "city": "Taoyuan",
      "state": "Taoyuan City",
      "zipCode": "330"
    },
    {
      "address": "No. 99, Wenhua Rd",
      "city": "Taipei",
      "state": "Taipei City",
      "zipCode": "105"
    },
    {
      "address": "No. 35, Chenggong Rd",
      "city": "Kaohsiung",
      "state": "Kaohsiung City",
      "zipCode": "801"
    },
    {
      "address": "No. 18, Dadun Rd",
      "city": "Taichung",
      "state": "Taichung City",
      "zipCode": "408"
    }
  ],
  "United Kingdom": [
    {
      "address": "10 Downing Street",
      "city": "London",
      "state": "Greater London",
      "zipCode": "SW1A 2AA"
    },
    {
      "address": "221B Baker Street",
      "city": "London",
      "state": "Greater London",
      "zipCode": "NW1 6XE"
    },
    {
      "address": "1 Piccadilly",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zipCode": "M1 1RG"
    },
    {
      "address": "45 Deansgate",
      "city": "Manchester",
      "state": "Greater Manchester",
      "zipCode": "M3 2AY"
    },
    {
      "address": "12 New Street",
      "city": "Birmingham",
      "state": "West Midlands",
      "zipCode": "B2 4QA"
    },
    {
      "address": "100 Princes Street",
      "city": "Edinburgh",
      "state": "Scotland",
      "zipCode": "EH2 3AA"
    },
    {
      "address": "8 George Square",
      "city": "Glasgow",
      "state": "Scotland",
      "zipCode": "G2 1DY"
    },
    {
      "address": "30 Park Row",
      "city": "Leeds",
      "state": "West Yorkshire",
      "zipCode": "LS1 5JD"
    },
    {
      "address": "20 Queen Square",
      "city": "Bristol",
      "state": "South West England",
      "zipCode": "BS1 4ND"
    },
    {
      "address": "15 Grey Street",
      "city": "Newcastle",
      "state": "Tyne and Wear",
      "zipCode": "NE1 6EE"
    }
  ],
  "United States": [
    {
      "address": "350 5th Ave",
      "city": "New York",
      "state": "New York",
      "zipCode": "10118"
    },
    {
      "address": "405 Lexington Ave",
      "city": "New York",
      "state": "New York",
      "zipCode": "10174"
    },
    {
      "address": "1 Market St",
      "city": "San Francisco",
      "state": "California",
      "zipCode": "94105"
    },
    {
      "address": "1600 Amphitheatre Pkwy",
      "city": "Mountain View",
      "state": "California",
      "zipCode": "94043"
    },
    {
      "address": "1 Microsoft Way",
      "city": "Redmond",
      "state": "Washington",
      "zipCode": "98052"
    },
    {
      "address": "233 S Wacker Dr",
      "city": "Chicago",
      "state": "Illinois",
      "zipCode": "60606"
    },
    {
      "address": "600 Congress Ave",
      "city": "Austin",
      "state": "Texas",
      "zipCode": "78701"
    },
    {
      "address": "700 Exposition Park Dr",
      "city": "Los Angeles",
      "state": "California",
      "zipCode": "90037"
    },
    {
      "address": "401 Biscayne Blvd",
      "city": "Miami",
      "state": "Florida",
      "zipCode": "33132"
    },
    {
      "address": "151 3rd St",
      "city": "San Francisco",
      "state": "California",
      "zipCode": "94103"
    }
  ]
};

const LOCAL_VERIFIED_ADDRESS_POOL_META = {
  "generatedAt": "2026-05-10T14:13:10.154Z",
  "countryCount": 19,
  "totalEntries": 190,
  "minEntriesPerCountry": 10,
  "maxEntriesPerCountry": 10,
  "minCitiesPerCountry": 5,
  "countryStats": {
    "Australia": {
      "entries": 10,
      "cities": 9
    },
    "Brazil": {
      "entries": 10,
      "cities": 8
    },
    "Canada": {
      "entries": 10,
      "cities": 6
    },
    "China": {
      "entries": 10,
      "cities": 8
    },
    "France": {
      "entries": 10,
      "cities": 9
    },
    "Germany": {
      "entries": 10,
      "cities": 9
    },
    "Hong Kong": {
      "entries": 10,
      "cities": 5
    },
    "India": {
      "entries": 10,
      "cities": 8
    },
    "Italy": {
      "entries": 10,
      "cities": 8
    },
    "Japan": {
      "entries": 10,
      "cities": 9
    },
    "Mexico": {
      "entries": 10,
      "cities": 6
    },
    "Netherlands": {
      "entries": 10,
      "cities": 8
    },
    "Russia": {
      "entries": 10,
      "cities": 8
    },
    "Singapore": {
      "entries": 10,
      "cities": 6
    },
    "South Korea": {
      "entries": 10,
      "cities": 9
    },
    "Spain": {
      "entries": 10,
      "cities": 8
    },
    "Taiwan": {
      "entries": 10,
      "cities": 6
    },
    "United Kingdom": {
      "entries": 10,
      "cities": 8
    },
    "United States": {
      "entries": 10,
      "cities": 8
    }
  }
};

if (typeof window !== 'undefined') {
  window.LOCAL_VERIFIED_ADDRESS_POOL = LOCAL_VERIFIED_ADDRESS_POOL_DATA;
  window.LOCAL_VERIFIED_ADDRESS_POOL_META = LOCAL_VERIFIED_ADDRESS_POOL_META;
}

if (typeof globalThis !== 'undefined') {
  globalThis.LOCAL_VERIFIED_ADDRESS_POOL = LOCAL_VERIFIED_ADDRESS_POOL_DATA;
  globalThis.LOCAL_VERIFIED_ADDRESS_POOL_META = LOCAL_VERIFIED_ADDRESS_POOL_META;
}
